[execute]
description = "Executes server sided code."
aliases = ["execute", "c"]
useCases = [["code"]]

[localExecute]
description = "Executes client sided code."
aliases = ["localExecute", "cl", "l", "x"]
useCases = [["code"]]
