_prefixes = ["get", "g"]

[commands]
description = "Shows a list of commands."
aliases = ["commands", "cmds", "help"]

[base]
description = "Adds a base."
aliases = ["base", "b"]

[noBase]
description = "Removes the base."
aliases = ["noBase", "nb"]

[respawn]
description = "Respawns your character."
aliases = ["respawn", "r"]

[refresh]
description = "Respawns your character at your current location."
aliases = ["refresh", "re", "spotRespawn", "spotReset", "sr"]

[nil]
description = "Removes your character."
aliases = ["nil"]

[clear]
description = "Clears workspace."
aliases = ["clear", "c"]

[fixCamera]
description = "Fixes your camera."
aliases = ["fixCamera", "fixCam", "fc"]

[noGui]
description = "Removes all guis."
aliases = ["noGui", "nog", "ng"]

[rig6]
description = "Converts your character to a 6 limb rig."
aliases = ["rig6", "r6"]

[rig15]
description = "Converts your character to a 15 limb rig."
aliases = ["rig15", "r15"]

[rig6dummy]
description = "Spawns a 6 limb rig at your location."
aliases = ["rig6dummy", "r6dummy", "dummy", "d"]

[rig15dummy]
description = "Spawns a 15 limb rig at your location."
aliases = ["rig15dummy", "r15dummy", "rdummy", "rd"]

[noScripts]
description = "Stops all local scripts and server scripts ran by you."
aliases = ["noScripts", "nos", "ns"]

[noServerScripts]
description = "Stops all server scripts ran by you."
aliases = ["noServerScripts", "noss", "nss"]

[noLocalScripts]
description = "Stops all local scripts."
aliases = ["noLocalScripts", "nls"]
