_prefixes = ["get", "g"]

[commands]
description = "Shows a list of commands."
aliases = ["commands", "cmds", "help"]

[base]
description = "Adds a base."
aliases = ["base", "b"]

[noBase]
description = "Removes the base."
aliases = ["noBase", "nb"]

[respawn]
description = "Respawns your character."
aliases = ["respawn", "r"]

[refresh]
description = "Respawns your character at your current location."
aliases = ["refresh", "re", "spotRespawn", "spotReset", "sr"]

[nil]
description = "Removes your character."
aliases = ["nil"]

[clear]
description = "Clears workspace."
aliases = ["clear", "c"]

[fixCamera]
description = "Fixes your camera."
aliases = ["fixCamera", "fixCam", "fc"]

[rig6]
description = "Converts your character to a 6 limb rig."
aliases = ["rig6", "r6"]

[rig15]
description = "Converts your character to a 15 limb rig."
aliases = ["rig15", "r15"]
